services:
  - type: web
    name: makmus-pocketbase
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: pb_data
      mountPath: /pb/pb_data
      sizeGB: 1
